---
- name: NGINX proxy configuration (1)
  become: true
  file:
    path: "{{ proxy_configuration_folder }}"
    state: directory
    owner: "{{ ansible_user}}"
    group: "{{ ansible_user}}"

- name: NGINX proxy configuration (2)
  copy:
    src: "proxy.conf"
    dest: "{{ proxy_configuration_folder }}/proxy.conf"

- name: Start NGINX proxy
  docker_container:
    name: nginx-reverse-proxy
    image: "{{ proxy_image }}"
    pull: yes
    detach: true
    state: started
    recreate: yes
    restart_policy: "unless-stopped"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "{{ proxy_configuration_folder }}/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro"
      - "{{ certificates_folder }}:/etc/nginx/certs"
    env:
      ENABLE_IPV6: "true"
    ports:
      - "80:80"
      - "443:443"
