---
- name: Start / Stop EC2 instances
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    enable: true
  tasks:
    - name: Gather facts
      amazon.aws.ec2_instance_info:
        region: eu-central-1
        filters:
          tag:application: jenkins
          instance-state-name: "{{ enable | bool | ternary('stopped','running') }}"
      register: ec2_info

    - name: "EC2 Lifecycle"
      amazon.aws.ec2_instance:
        state: "{{ enable | bool | ternary('running','stopped') }}"
        instance_ids: "{{item.instance_id}}"
      with_items: "{{ec2_info.instances}}"
