service: update-dns-record

plugins:
  - serverless-go-plugin

provider:
  name: aws
  architecture: arm64
  runtime: provided.al2
  versionFunctions: false
  memorySize: 128
  timeout: 30
  region: eu-central-1
  endpointType: REGIONAL
  profile: serverless-admin-profile
  logRetentionInDays: 7
  iam:
    role: MyRole
  tags:
    application: "ec2-dns-updater"
    owner: "serverless"
  stackTags:
    application: "ec2-dns-updater"
    owner: "serverless"
  deploymentBucket:
    blockPublicAccess: true
    tags:
      application: "ec2-dns-updater"
      owner: "serverless"
  environment:
    REGION: ${self:provider.region}
    HOSTED_ZONE_ID: ZWC66FN0XU6P9
custom:
  go:
    supportedRuntimes: provided.al2
    buildProvidedRuntimeAsBootstrap: true
    cmd: GOARCH=arm64 GOOS=linux go build -ldflags="-s -w"

functions:
  update-dns-record:
    handler: cmd/main.go
    name: ec2-dns-updater
    events:
      - eventBridge:
          pattern:
            source:
              - "aws.ec2"
            detail-type:
              - "EC2 Instance State-change Notification"
            detail:
              state:
                - running

resources:
  Resources:
    MyRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ec2-auto-update-route53-record-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ec2-auto-update-route53-record
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:TagResource
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/*:*:*"
                - Effect: "Allow"
                  Action:
                    - ec2:DescribeInstances
                    - ec2:DescribeTags
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                    - route53:ListHostedZones
                    - route53:ChangeResourceRecordSets
                  Resource: "*"
        Tags:
          - Key: application
            Value: ec2-dns-updater
          - Key: owner
            Value: serverless
